### ISSUE TITLE
DB always locked when running rqlite, even for reads.

### ISSUE THREAD

**Issue by tchoulihan** [otoolep/rqlite#14]
I have a case where I prefer to read from the local sqlite db file directly with my own sqlite jdbc driver. I want to do this mainly for speed, and because I'm using an ORM framework that makes reading and constructing write statements for rql easier.

But whenever RQL is running, it completely locks the db.sqlite file from reading.

Here's the relevant part of the stack trace error I'm getting:
```
Caused by: java.sql.SQLException: [SQLITE_BUSY]  The database file is locked (database is locked)
	at org.sqlite.DB.newSQLException(DB.java:383)
	at org.sqlite.DB.newSQLException(DB.java:387)
	at org.sqlite.DB.throwex(DB.java:374)
	at org.sqlite.NativeDB.prepare(Native Method)
	at org.sqlite.DB.prepare(DB.java:123)
	at org.sqlite.PrepStmt.<init>(PrepStmt.java:42)
```

**Comment by tchoulihan** [comment]
Update to this:

I added a Thread.sleep to see if waiting after RQL has initialized would work.

It seems that waiting around 5 seconds after RQL has started seems to unlock the DB. It also seems that additional writes must not lock the DB for long periods of time at all, because I've done some stress testing, and I haven't run into another locking issue since.

You can close this out if you want, or add this bit about the locking into the documentation, or possibly see if there is any way to release the DB lock quickly after initializing. 

Thanks.

**Comment by otoolep** [comment]
OK, this is interesting. Let me see if I can repro your findings and see why this is happening.

**Comment by otoolep** [comment]
Can you try something else? Instead of simply waiting 5 seconds, can you instead block from accessing the database until the `/diagnostics` endpoint returns with 200? Once that returns, then check if the local sqlite copy is readable.

I am wondering if you're not waiting for the node to fully initialize, but the endpoint above should only return once the node is ready.

**Comment by tchoulihan** [comment]
Just tested this endpoint. Unfortunately the diagnostics endpoint is immediately available after startup, while there is still a DB lock.

**Comment by otoolep** [comment]
I can't repro this issue. I start rqlite and immediately have `sqlite3` read the database. It has no problems doing so, and I don't need any delays.

Can you produce a bash script that reproduce this? The simple script shown below tells me the database is available for reads once the HTTP endpoint is responsive:

```$ cat test.sh 
./rqlite -p 4002 ~/node.2 &
while true; do
    curl localhost:4002/diagnostics
    if [ $? -eq 0 ]; then
        break
    fi
done
echo "SELECT * from foo;" | sqlite3 ~/node.2/db.sqlite
```

**Comment by tchoulihan** [comment]
You're right. I just tested this script myself and it works fine. Not sure whats going on with my end, but I can reopen this issue if I find more problems.

**Comment by tchoulihan** [comment]
Hey @otoolep , I'm getting this issue again. As I've added more data to the rqlite DB, the locking issue when starting up is becoming worse. Now, after starting up rqlite, it seems to need about 2 minutes to unlock the database. 

When watching the folder after rqlite has already started up, it looks like a db.sqlite-journal keeps being altered/changed, for up to a few minutes, causing a lock. It can't be a syncing issue, because right now I'm only running 1 node.

**Comment by otoolep** [comment]
- Is all your testing with a single node right now?
- How large is your database?
- Have you tried reproducing read failures during this time by using `sqlite`?

**Comment by tchoulihan** [comment]
> Is all your testing with a single node right now? 

Yep.

> How large is your database?

About 80Kb.

> Have you tried reproducing read failures during this time by using sqlite?

Yep, running the sqlite3 .tables command won't show anything. using sqlitebrowser also shows it as locked.

**Comment by tchoulihan** [comment]
Some other things I've noticed. 

When starting up rqlite, my DB drops a bunch in size, down to maybe 60kb. A db.sqlite-journal file appears to be altering the DB for the few minutes while its locked, growing it back up to the original size.

**Comment by otoolep** [comment]
How is the node being shut down, before the restart? Just killing the process? SIGTERM or SIGKILL?

**Comment by otoolep** [comment]
Does this happen every time now? Any chance you could send me the database (by e-mail, perhaps?)

**Comment by tchoulihan** [comment]
Using unix kill, so I think that's a SIGTERM. Is there a proper way to shut down rqlite?

**Comment by tchoulihan** [comment]
Actually sorry, I'm using kill -9 , which is a sigkill.

**Comment by otoolep** [comment]
OK.

SIGKILL should be OK, sqlite is meant to handle that fine. With your database, does this happen 100% of the time?

**Comment by tchoulihan** [comment]
Yep, every time it's restarted.

**Comment by otoolep** [comment]
Hmm, OK. I can try to load in some records and see if I can repro it. How many records do you have? How many tables? Can you share your schema?

**Comment by tchoulihan** [comment]
Sure, would just giving you the db.sqlite file be enough?

**Comment by tchoulihan** [comment]
Or the whole directory?

**Comment by otoolep** [comment]
I think `db.sqlite` would be sufficient, once it's all settled. You can e-mail it to me if you like (address on my profile).

**Comment by tchoulihan** [comment]
k, done

**Comment by otoolep** [comment]
OK @tchoulihan -- I went back to the source, to remind myself about the start-up scenario. This is what is happening, and it's an intrinsic part of the way the system works.

When a node is restarted, the Raft log is re-applied to the database so that the system returns to the state it was in before it was killed. This is the point of the Raft design, as it is based on a distributed log. Of course, over time this log would get very large as there is an entry in there for every change to the database that ever took place. That is why rqlite supports snapshotting -- snapshots make a copy of the database, and then truncate the log up that point. On start-up, if a snaphot exists, the database is recreated from the snapshot and only log entries (changes to the database) that took place after the snap was created are then applied. This means the system starts up much quicker when there is a snapshot available, relative to replaying the entire log from the start of time.

rqlite, by default, creates a snapshot every 1,000 changes. This means on restart the node may need to re-apply up to 1,000 changes to get back to a consistent state. I didn't give 1,000 too much thought, and it seems too high for your system. Try changing it to 100, or even 50, which will mean quicker restart times. With a setting of 100, it means at most there will be 100 changes that need to be applied to the database, which should be much faster than 1,000. You might need to go lower. Snaps aren't free of course, as they consume processing power and disk IO (not too much in practise however). It's trade-off between the generating snaps and faster start-up times.

To control the snapshot threshold, pass `-s` at start-up to all your nodes. For example:

rqlite -s 50

So try launching your nodes with this param (or lower) and see how long the database is locked on start up. Make sure performance isn't too badly affected for you. You may need to write another 50 changes to the database to get an actual snap to happen for an existing system. 

Let me know if you have any questions, and if this solves your issue.

**Comment by otoolep** [comment]
I have also reduced the default snap setting to 100.

**Comment by tchoulihan** [comment]
This was easy for me to test because I have a setup where I can delete and regenerate rqlite quickly. 

I tried -s 50, and some lower values, and it does seem to create some snapshot files where I had none before. I notice that whereas the DB use to decrease to a far lower size, now it only decreases to around 75% of what it once was, taking a lot less time to build back up and release the lock.

That pretty much fixes my problem, thanks @otoolep .

**Comment by otoolep** [comment]
Great @tchoulihan -- systems like this sometimes a non-trivial startup time as they recover state. It's a tradeoff between making those snapshots and start-up time. In a real system, nodes may not actually be started *that* often, so a longer start-up time every so often may not be a problem.

I am looking into ways of making the startup even quicker without setting the snapshot threshold that low.  https://github.com/otoolep/rqlite/issues/19
