### ISSUE TITLE
Version and Changelog

### ISSUE THREAD

**Issue by fern4lvarez** [otoolep/rqlite#22]
This project lacks of versioning. It might help users and developers on tracking changes, making it easier to take decisions on possible upgrades. It will ease the release process, when it comes of native packages (i.e. apt, brew, rpm...).

This versioning should adheres to [Semantic Versioning](http://semver.org/) and bring a `CHANGELOG` file following http://keepachangelog.com/ practices.

Main question here is, which versions do we want to start with? Does `0.1.0` sound good? Do we want to include any specific work in progress to `0.1.0` before releasing?

**Comment by otoolep** [comment]
There are two pieces of work I'd like to see done:

-- make it possible to disable leader redirection, via a switch at the command line. This was introduced in https://github.com/otoolep/rqlite/commit/106296515fd393f1091130245f4b386c4f93fb78, but it should be controllable by a switch, since not everyone wants it.
-- it would be nice to get https://github.com/otoolep/rqlite/issues/19 done.

**Comment by otoolep** [comment]
This is done well enough now, now that rqlite has a changelog and uses the Github releases pages. We might do packages in the future.
