### ISSUE TITLE
Create ability to backup node

### ISSUE THREAD

**Issue by otoolep** [otoolep/rqlite#57]
The system should expose an API endpoint that streams out a consistent snapshot of the database.

**Comment by zmedico** [comment]
Binary copy of sqlite database, or text sql dump? Maybe one endpoint for each?

**Comment by otoolep** [comment]
I was thinking binary copy of the SQLite database file. With one you can always get the other yourself.

**Comment by otoolep** [comment]
Actually, this is more complex. To completely back up a node, the system needs to backup the SQLite database *and* the associated Raft data. Only that way could a node be completely restored.

The backup of the database file can be achieved by using the `backup` call on the Go library, to copy the database file to a temp file. Then that temp file can be part of the backup.

Alternatively, if backup is just going to lock the entire system (may necessary for full Raft backup) then we might as well just copy the database file directly since it won't be capable of being changed during the copying.

**Comment by zmedico** [comment]
A global lock makes sense. The length of time that the lock is held can be minimized to the time it takes to create a consistent copy of the whole state. The backup consumer can never assume that the backup it receives is entirely up-to-date, since changes can happen as soon as the backup completes (unless there is a procedure to put the whole system into an immutable mode).

**Comment by otoolep** [comment]
There is a backup endpoint in place, but it is not fully functional. The binary dump is not yet correct.

**Comment by otoolep** [comment]
This is done. Check the README for details.
